//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDroid2
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ListBackground = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int StateInGame = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int StateOffline = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int StateOnline = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int text = 2130968581;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_disabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_enabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DefaultAvatar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int edit_text = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int gradient = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int LauncherIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int NotificationIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int steamdroid_logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int txt_background = 2130837516;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int ButtonConnect = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int ButtonFriends = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int ButtonSend = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int ChatMessage = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int ChatName = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int FriendGame = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int FriendName = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int FriendState = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int ImageAvatar = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int ListOutput = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int TextInput = 2131230728;
			
			// aapt resource value: 0x7f080014
			public const int button_disconnect = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int button_settings = 2131230741;
			
			// aapt resource value: 0x7f08000f
			public const int button_state_1 = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int button_state_2 = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int button_state_3 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int button_state_4 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int button_state_5 = 2131230739;
			
			// aapt resource value: 0x7f08000d
			public const int image_background = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int image_header = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout1 = 2131230727;
			
			// aapt resource value: 0x7f08000e
			public const int menu_change_state = 2131230734;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdapterChat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AdapterFriends = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Chat = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Friends = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Preferences = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int OptionsMenu = 2131165184;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Send = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int change_state = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int connect = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int disconnect = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int exit = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int friends = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int settings = 2131034116;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int SteamStyle = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int steam_edittext = 2131099649;
			
			private Style()
			{
			}
		}
	}
}
