//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDroid2
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int ListBackground = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int StateInGame = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int StateOffline = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int StateOnline = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_disabled = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_enabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_style = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int DefaultAvatar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LauncherIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int NotificationIcon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int steamdroid_logo = 2130837512;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int ButtonChangeState = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int ButtonConnect = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int ButtonDisconnect = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int ButtonExit = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int ButtonFriends = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int ButtonSend = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int ButtonSettings = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int ChatMessage = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int ChatName = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int FriendGame = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int FriendName = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int FriendState = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int ImageAvatar = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int ListOutput = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int TextInput = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int imageView1 = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdapterChat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AdapterFriends = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Chat = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Friends = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Preferences = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Send = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int change_state = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int connect = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int disconnect = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int exit = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int friends = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int settings = 2131034116;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int SteamStyle = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
