//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDroid2
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int ListBackground = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int StateInGame = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int StateOffline = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int StateOnline = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int background = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int text = 2131034117;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_disabled = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_enabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_style = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int DefaultAvatar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int edit_text = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int gradient = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int LauncherIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int NotificationIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int steamdroid_logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int txt_background = 2130837516;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000b
			public const int ButtonConnect = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int ButtonFriends = 2131296268;
			
			// aapt resource value: 0x7f090009
			public const int ButtonSend = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int ChatMessage = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int ChatName = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int FriendGame = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int FriendName = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int FriendState = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int ImageAvatar = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int ListOutput = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int TextInput = 2131296264;
			
			// aapt resource value: 0x7f090014
			public const int button_disconnect = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int button_settings = 2131296277;
			
			// aapt resource value: 0x7f09000f
			public const int button_state_1 = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int button_state_2 = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int button_state_3 = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int button_state_4 = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int button_state_5 = 2131296275;
			
			// aapt resource value: 0x7f09000d
			public const int image_background = 2131296269;
			
			// aapt resource value: 0x7f09000a
			public const int image_header = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int linearLayout1 = 2131296263;
			
			// aapt resource value: 0x7f09000e
			public const int menu_change_state = 2131296270;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdapterChat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AdapterFriends = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Chat = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Friends = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Preferences = 2130903045;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int OptionsMenu = 2131230720;
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Message = 2130968576;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int Send = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int change_state = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int connect = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int disconnect = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int exit = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int friends = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int settings = 2131099652;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int SteamStyle = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int steam_edittext = 2131165185;
			
			private Style()
			{
			}
		}
	}
}
